---
title: "task_1_pa_seminar"
format: html
---



```{r}


library(tidyverse)


wwbi <- read_csv("wwbi_data.csv")



```

```{r}


norge <- wwbi |>
  filter(indicator_code == "BI.EMP.FRML.PB.ZS")|>
  filter(country_code == "NOR")

print(unique(norge$year))
```

Vi får at det bare er registrert data for andelen sysselsatte i offenlig sektor i Norge i 2017. 

Skal lage et boksplott, som visser andelen av sysselsatte som er i offenlig sektor, der de er grupert på år.
```{r}

library(scales)

glimpse(wwbi)
boksplott <- wwbi |>

  filter(indicator_code == "BI.EMP.FRML.PB.ZS")|> 
  ggplot(aes(x = year, y = value)) + 
  geom_boxplot(aes(group = year)) + 
  scale_x_continuous(breaks = seq(2000,2020,1),
                     labels = seq(2000,2020,1)) +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  #heller dataen 45 grader 

  

boksplott
```

Vi ser at median andel falt dramatisk i 2008, samt i 2015. Dette henger sammen med finanskrisen og  oljeprisfallet.

```{r}
library(scales)

gdp <- read_csv("gdp.csv")

total_tibble <- gdp |>
  left_join(wwbi, by = join_by(country_code, year))|>
  filter(indicator_code == "BI.EMP.FRML.PB.ZS")|> 
  
  #fjerner urelavente verdier
  drop_na()


scatter <- total_tibble|>
  ggplot() + 
  geom_point(aes(x = (gdp_cap), y = value,alpha = 0.5)) + #legge på en alpha, slik at man kan fange opp at punktene overlapper
  scale_x_log10(label = label_comma(scale = 1e-3)) 

scatter 


```


```{r}  

#tar bare vare på den siste verdiern
wwbi_max <- wwbi |>
  filter(indicator_code == "BI.EMP.FRML.PB.ZS")|> 
  filter(year == max(year), .by = c(country_code))

View(wwbi_max)


```
